plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
}

ext {
    springCloudVersion = '2025.1.2'
    springAiVersion = '2.0.1' // Spring Boot 4.1에 호환되는 Spring AI 2.0 버전 정의
}

allprojects {
    group = 'com.sparta'
    version = '0.0.1-SNAPSHOT'
    description = 'sixfin'
    repositories {
        mavenCentral()
        // Spring AI Milestone 및 Snapshot 패키지를 다운로드하기 위한 저장소
        maven { url 'https://repo.spring.io/milestone' }
        maven { url 'https://repo.spring.io/snapshot' }
    }

}

subprojects {
    apply plugin: 'java'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'

    java {
        sourceCompatibility = JavaVersion.VERSION_21
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
            mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
        }
    }

    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-validation'
        //implementation 'org.springframework.boot:spring-boot-starter-webmvc'
        implementation 'org.springframework.boot:spring-boot-starter-zipkin'
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'
        testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
        //testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
        testImplementation 'org.springframework.boot:spring-boot-starter-zipkin-test'
        testCompileOnly 'org.projectlombok:lombok'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
        testAnnotationProcessor 'org.projectlombok:lombok'
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
}