-- ============================================================
-- 시세 데이터 (stocks / daily_candles / price_candles) DDL
--
-- 참고용 스크립트다. 실제 스키마는 spring.jpa.hibernate.ddl-auto=update 로
-- 엔티티에서 자동 생성되므로 애플리케이션이 이 파일을 실행하지는 않는다.
-- 수동으로 스키마를 미리 만들어보거나 검토할 때 psql / IntelliJ DB 콘솔에서 실행한다.
-- ============================================================

-- ----------------------------------------
-- 종목
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS p_stocks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol      VARCHAR(20)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    market      VARCHAR(20)  NOT NULL,
    currency    VARCHAR(3)   NOT NULL,
    is_active   BOOLEAN      NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ,
    CONSTRAINT uk_stocks_symbol UNIQUE (symbol)
);

-- ----------------------------------------
-- 일봉 (20일 최고가 등 진단 지표 계산용, 1년치)
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS p_daily_candles (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id          BIGINT        NOT NULL REFERENCES p_stocks (id),
    trade_date        DATE          NOT NULL,
    open_price        NUMERIC(19,4) NOT NULL,
    high_price        NUMERIC(19,4) NOT NULL,
    low_price         NUMERIC(19,4) NOT NULL,
    close_price       NUMERIC(19,4) NOT NULL,
    volume            BIGINT        NOT NULL,
    recent_20d_high   NUMERIC(19,4),
    recent_20d_low    NUMERIC(19,4),
    recent_5d_return  NUMERIC(7,2),
    created_at        TIMESTAMPTZ   NOT NULL,
    CONSTRAINT uk_daily_candle UNIQUE (stock_id, trade_date)
);

CREATE INDEX IF NOT EXISTS idx_daily_candle_stock ON p_daily_candles (stock_id);

-- ----------------------------------------
-- 1분봉 (가상 시계 리플레이 원본, seq는 전 종목 공통 시간축)
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS p_price_candles (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id          BIGINT        NOT NULL REFERENCES p_stocks (id),
    seq               BIGINT        NOT NULL,
    market_time       TIMESTAMPTZ   NOT NULL,
    open_price        NUMERIC(19,4) NOT NULL,
    high_price        NUMERIC(19,4) NOT NULL,
    low_price         NUMERIC(19,4) NOT NULL,
    close_price       NUMERIC(19,4) NOT NULL,
    volume            BIGINT        NOT NULL,
    recent_20d_high   NUMERIC(19,4),
    recent_20d_low    NUMERIC(19,4),
    recent_5d_return  NUMERIC(7,2),
    created_at        TIMESTAMPTZ   NOT NULL,
    CONSTRAINT uk_price_candle UNIQUE (stock_id, seq)
);

-- 리플레이 스케줄러가 "현재 seq 이하만" 조회할 때 사용 (candles P1 API도 동일)
CREATE INDEX IF NOT EXISTS idx_price_candle_seq ON p_price_candles (seq);
