-- ============================================================
-- 시세 데이터 (stocks / daily_candles / price_candles) DDL
--
-- ddl-auto: validate 사용 중이라 Hibernate가 스키마를 만들어주지 않는다.
-- 로컬에서 앱을 처음 띄우기 전에 psql / IntelliJ DB 콘솔에서 이 파일을 직접 실행해야 한다.
-- application-local.yml의 currentSchema=trading_service와 맞춰 스키마를 명시한다.
-- ============================================================

CREATE SCHEMA IF NOT EXISTS trading_service;

-- ----------------------------------------
-- 종목
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS trading_service.p_stocks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol      VARCHAR(20)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    market      VARCHAR(20)  NOT NULL,
    currency    VARCHAR(3)   NOT NULL,
    is_active   BOOLEAN      NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ,
    CONSTRAINT uk_stocks_symbol UNIQUE (symbol)
);

-- ----------------------------------------
-- 일봉 (20일 최고가 등 진단 지표 계산용, 1년치)
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS trading_service.p_daily_candles (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id          BIGINT        NOT NULL REFERENCES trading_service.p_stocks (id),
    trade_date        DATE          NOT NULL,
    open_price        NUMERIC(19,4) NOT NULL,
    high_price        NUMERIC(19,4) NOT NULL,
    low_price         NUMERIC(19,4) NOT NULL,
    close_price       NUMERIC(19,4) NOT NULL,
    volume            BIGINT        NOT NULL,
    recent_20d_high   NUMERIC(19,4),
    recent_20d_low    NUMERIC(19,4),
    recent_5d_return  NUMERIC(7,2),
    created_at        TIMESTAMPTZ   NOT NULL,
    CONSTRAINT uk_daily_candle UNIQUE (stock_id, trade_date)
);

CREATE INDEX IF NOT EXISTS idx_daily_candle_stock ON trading_service.p_daily_candles (stock_id);

-- ----------------------------------------
-- 1분봉 (가상 시계 리플레이 원본, seq는 전 종목 공통 시간축)
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS trading_service.p_price_candles (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id          BIGINT        NOT NULL REFERENCES trading_service.p_stocks (id),
    seq               BIGINT        NOT NULL,
    market_time       TIMESTAMPTZ   NOT NULL,
    open_price        NUMERIC(19,4) NOT NULL,
    high_price        NUMERIC(19,4) NOT NULL,
    low_price         NUMERIC(19,4) NOT NULL,
    close_price       NUMERIC(19,4) NOT NULL,
    volume            BIGINT        NOT NULL,
    recent_20d_high   NUMERIC(19,4),
    recent_20d_low    NUMERIC(19,4),
    recent_5d_return  NUMERIC(7,2),
    created_at        TIMESTAMPTZ   NOT NULL,
    CONSTRAINT uk_price_candle UNIQUE (stock_id, seq)
);


-- ----------------------------------------
-- orders(임시 — Orders 도메인 소유자 확정 전까지 로컬 기동용 스텁)
-- BaseEntity 감사 컬럼 포함해야 ddl-auto: validate 통과함
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS trading_service.p_orders (
    id          UUID PRIMARY KEY,
    created_at  TIMESTAMP,
    created_by  UUID,
    updated_at  TIMESTAMP,
    updated_by  UUID,
    deleted_at  TIMESTAMP,
    deleted_by  UUID
);

-- 리플레이 스케줄러가 "현재 seq 이하만" 조회할 때 사용 (candles P1 API도 동일)
CREATE INDEX IF NOT EXISTS idx_price_candle_seq ON trading_service.p_price_candles (seq);
