spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/sixfin?currentSchema=trading_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

market-data:
  csv-dir: ${MARKET_DATA_DIR:../tools/market-data-collector/out}