spring:
  application:
    name: trading-service
  profiles:
    active: local
  Kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

market:
  clock:
    start-seq: 0
    end-seq: 7393       # recent_20d_high가 NULL 되기 직전. 일봉 보강 시 7783으로 확장
    speed-factor: 1
    cache-refresh-interval-ms: 1000

server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

  instance:
    # 호스트명 대신 IP 주소를 Eureka에 등록
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v1/spans